config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles, only: [:index, :show, :new, :create] do
    get 'search', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to @article
    else
      render action: 'new'
    end
  end

  # GET /articles/search
  def search
    query = "%#{params[:query]}%"
    @articles = Article
      .where('title like ? or description like ? or url like ?',
             query, query, query)
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :description, :url, :submitter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<p>
  <%= link_to 'Add Article', new_article_path %>
</p>

<br />

<ul class="unstyled">
  <% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article %>
  </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<div class="form-actions">
  <h1>Submit Article</h1>

  <p>Use the form below to submit a new article to Launcher News.</p>
</div>

<%= form_for(@article, html: { class: 'form-horizontal' }) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :url, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :url %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Back', articles_path, class: 'btn' %>
  </div>
<% end %>

app/views/articles/search.html.erb
<h1>Search Results</h1>

<br />

<% if @articles.empty? %>

<p>No results found.</p>

<% else %>

<p><%= "#{@articles.count} result(s) found." %></p>

<ul class="unstyled">
  <% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article %>
  </li>
  <% end %>
</ul>
<% end %>

app/views/articles/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @article.url, @article.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Launcher News" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/css/foundation.min.css' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
          <li class="name">
            <h1><%= link_to "Launcher News", root_path %></h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li class="has-form">
              <div class="row collapse">
                <%= form_tag(search_articles_path, method: :get) do %>
                  <div class="large-8 small-9 columns">
                    <%= text_field_tag 'query', params[:query], placeholder: 'Enter search term...' %>
                  </div>
                  <div class="large-4 small-3 columns">
                    <%= submit_tag 'Search', class: 'alert button expand' %>
                  </div>
                <% end %>
              </div>
            </li>
          </ul>
        </section>
      </nav>
    </div>

    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.3/js/foundation.min.js' %>
  </body>
</html>